  - name: 'Handlers : Restart systemd service: "slurmdbd.service"'
    become: true
    ansible.builtin.systemd_service:
      name: slurmdbd
      state: restarted
      daemon-reload: true

  - name: 'Handlers : Restart systemd service: "slurmctld.service"'
    become: true
    ansible.builtin.systemd_service:
      name: slurmctld
      state: restarted
      daemon-reload: true

  - name: 'Handlers : Restart systemd service: "slurmd.service"'
    become: true
    ansible.builtin.systemd_service:
      name: slurmd
      state: restarted
      daemon-reload: true