- name: 'Install : Download latest slurm package'
  become: true
  ansible.builtin.get_url:
    url: "{{ slurm_download_url }}"
    dest: "{{ slurm_download_dir }}"
    owner: "slurm"
    group: "slurm"
    mode: '0644'

- name: 'Install : Unarchive slurm to "{{ slurm_download_dir }}"'
  become: true
  become_user: slurm
  vars: 
    ansible_shell_allow_world_readable_temp: true
  ansible.builtin.unarchive:
    src: "{{ slurm_download_dir }}/{{ slurm_package_name }}.{{ slurm_package_extension }}"
    dest: "{{ slurm_download_dir }}"
    owner: "slurm"
    group: "slurm"

- name: 'Install : Run slurm configure script'
  become: true
  become_user: slurm
  vars: 
    ansible_shell_allow_world_readable_temp: true
  ansible.builtin.shell:
  args:
    chdir: "{{ slurm_download_dir }}/{{ slurm_package_name }}"
    cmd: "./configure --prefix={{ slurm_prefix }}"

- name: 'Install : Run slurm make script'
  become: true
  become_user: slurm
  vars: 
    ansible_shell_allow_world_readable_temp: true
  ansible.builtin.shell:
  args:
    chdir: "{{ slurm_download_dir }}/{{ slurm_package_name }}"
    cmd: "make"

- name: 'Install : Run slurm make install script'
  become: true
  ansible.builtin.shell:
  args:
    chdir: "{{ slurm_download_dir }}/{{ slurm_package_name }}"
    cmd: "make install"

- name: 'Install : Set parameters for {{ slurm_sys_config_dir }}'
  become: true
  ansible.builtin.file:
    path: '{{ slurm_sys_config_dir }}'
    state: directory
    owner: slurm
    group: slurm
    mode: '0700'
#
#- name: 'Install : Set parameters for {{ munge_local_state_dir }}/lib/munge'
#  become: true
#  ansible.builtin.file:
#    path: '{{ munge_local_state_dir }}/lib/munge'
#    state: directory
#    owner: munge
#    group: munge
#    mode: '0700'
#
#- name: 'Install : Set parameters for {{ munge_local_state_dir }}/log/munge'
#  become: true
#  ansible.builtin.file:
#    path: '{{ munge_local_state_dir }}/log/munge'
#    state: directory
#    owner: munge
#    group: munge
#    mode: '0700'
#
#- name: 'Install : Set parameters for {{ munge_run_state_dir }}/munge'
#  become: true
#  ansible.builtin.file:
#    path: '{{ munge_run_state_dir }}/munge'
#    state: directory
#    owner: munge
#    group: munge
#    mode: '0755'
#
#- name: 'Install : Start munge daemon'
#  become: true
#  ansible.builtin.systemd_service:
#    name: munge
#    daemon_reload: true
#    state: started
#    enabled: true