- name: "Clean-up : Remove unarchived package {{ munge_package_name }}"
  ansible.builtin.file: 
    name: "{{ munge_download_dir }}/{{ munge_package_name }}"
    state: absent 

- name: "Clean-up : Remove  package archive {{ munge_package_name }}.{{ munge_package_extension }}"
  ansible.builtin.file: 
    name: "{{ munge_download_dir }}/{{ munge_package_name }}.{{ munge_package_extension }}"
    state: absent 