galaxy_info:
  author: Dmitrii Kondidatov (d.kondidatov@gmail.com)
  description: Ansible role for OpenMPI installation
  license: BSD-3-Clause
  min_ansible_version: 2.1
  galaxy_tags: []

dependencies: []