hpc-master-nodes:
  hosts:
    hpc-master-1:
      ansible_host: 172.30.128.86
      mariadb_port: 6819
      mariadb_databases:
        - name: slurm_acct_db
          replicate: false
      mariadb_users: 
        - name: slurm
          #host: 100.64.200.10
          password: 1234
          priv: "*.*:USAGE/slurm_acct_db.*:ALL"
          state: present
  vars:
    master_node: true

hpc-worker-nodes:
  hosts:
    hpc-worker-1:
      ansible_host: 172.30.128.68
    hpc-worker-2:
      ansible_host: 172.30.128.70
    hpc-worker-3:
      ansible_host: 172.30.128.73
  vars:
    worker_node: true
   