hpc_master_nodes:
  hosts:
    hpc_master_1:
      ansible_host: 172.30.128.86
      mariadb_port: 6819
      mariadb_databases:
        - name: slurm_acct_db
          replicate: false
      mariadb_users: 
        - name: slurm
          #host: 100.64.200.10
          password: 1234
          priv: "*.*:USAGE/slurm_acct_db.*:ALL"
          state: present
      roles:
        - fauust.mariadb
  vars:
    master_node: true

hpc_worker_nodes:
  hosts:
    hpc_worker_1:
      ansible_host: 172.30.128.68
    hpc_worker_2:
      ansible_host: 172.30.128.70
    hpc_worker_3:
      ansible_host: 172.30.128.73
  vars:
    worker_node: true
   