---
- hosts:
    - hpc_master_nodes
  become: true
  roles: 
    - fauust.mariadb
  vars: 
    mariadb_innodb_raw: |
      innodb_buffer_pool_size=2048M
      innodb_log_file_size=1024M
      innodb_lock_wait_timeout=900
      max_allowed_packet=16M
    mariadb_port: 3306
    mariadb_bind_address: 127.0.0.1
    mariadb_databases:
      - name: slurm_acct_db
        replicate: false
    mariadb_users: 
      - name: slurm
        password: 1234
        priv: "*.*:USAGE/slurm_acct_db.*:ALL"
        state: present

- hosts: 
    - hpc_master_nodes
    - hpc_worker_nodes
  become: true
  tasks:
    - name: 'Import : lustre-client role'
      include_role: 
        name: lustre-client
    
    - name: 'Import : awscli role'
      include_role: 
        name: awscli
    
    - name: 'Import : munge role'
      include_role: 
        name: munge
    
    - name: 'Import : openmpi role'
      include_role: 
        name: openmpi

    - name: 'Import : slurm role'
      vars: 
        slurm_skip_installation: false
      include_role: 
        name: slurm
