---
- hosts: localhost
  connection: local
  tasks:
    #- name: 'Import : awscli role'
    #  include_role: 
    #    name: awscli
    
    - name: 'Import : munge role'
      include_role: 
        name: munge