---
- hosts: 
    - hpc_master_nodes
    - hpc_worker_nodes
  become: true
  tasks:
    - name: 'Import : lustre-client role'
      include_role: 
        name: lustre-client

    - name: 'Import : awscli role'
      include_role: 
        name: awscli

    - name: 'Import : munge role'
      include_role: 
        name: munge
    
    #- name: 'Import : openmpi role'
    #  include_role: 
    #    name: openmpi
#
    #- name: 'Import : slurm role'
    #  include_role: 
    #    name: slurm

