- name: 'Install : Download the FSx signing key'
  ansible.builtin.get_url:
    url: https://fsx-lustre-client-repo-public-keys.s3.amazonaws.com/fsx-ubuntu-public-key.asc
    dest: /usr/share/keyrings/fsx-ubuntu-public-key.asc
  register: apt_key

- name: "Install : Update gpg key"
  block: 
    - name: 'Install : Remove previous dearmored key'
      become: true
      ansible.builtin.file:
        name: /usr/share/keyrings/fsx-ubuntu-public-key.asc.gpg
        state: absent

    - name: 'Install : Dearmor FSx signing key'
      become: true
      ansible.builtin.shell:
      args:
        cmd: gpg --dearmor /usr/share/keyrings/fsx-ubuntu-public-key.asc
  when: apt_key.changed

- name: 'Install : Add the FSx repository'
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/fsx-ubuntu-public-key.asc.gpg] https://fsx-lustre-client-repo.s3.amazonaws.com/ubuntu noble main"
    state: present

- name: 'Install : Install Lustre-cluent'
  become: true
  ansible.builtin.apt:
    autoremove: true
    pkg:
    - "lustre-client-modules-{{ aws_linux_version }}"

- name: 'Install : Mount lustre FSx'
  ansible.posix.mount:
    path: "{{ lustre_mount_path }}"
    src: "{{ lustre_mount_endpoint }}"
    fstype: lustre
    opts: realtime,flock
    state: present